const paths = {
  HOME: "/",
  PRODUCTS: "/products",
  CART: "/cart",
  ABOUT_US: "/about-us",
  PROFILE: "/profile",
  PROFILE_INFORMATION: "/profile/information",
  PROFILE_ORDERS: "/profile/orders",
  PROFILE_ORDERS_ALL: "/profile/orders/all",
  PROFILE_ORDERS_WAITING_CONFIRM: "/profile/orders/waiting-confirm",
  PROFILE_ORDERS_CONFIRM: "/profile/orders/confirm",
  PROFILE_ORDERS_DELIVERING: "/profile/orders/delivering",
  PROFILE_ORDERS_COMPLETE: "/profile/orders/complete",
  PROFILE_ORDERS_CANCEL: "/profile/orders/cancel",
  PROFILE_ORDERS_RETURN: "/profile/orders/return",
  PROFILE_BOOKINGS: "/profile/booking",
  PROFILE_VOUCHERS: "/profile/vouchers",
  LOGIN: "/login",
  REGISTER: "/register",
  SUPPORT: "/support",
  BOOKING: "/booking",
  ORDER_SUCCESS: "/order-success",
  ORDER_FAIL: "/order-fail",
};

export default paths;
